import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import http from 'node:http';
import {spawn,fork} from 'node:child_process';import {fileURLToPath} from 'node:url';import {once} from 'node:events';
import {laneFixture,git} from './fixtures/lane-setup.mjs';
import {BrainStore} from '../src/store.mjs';
import {LaneRegistry,gitWorkspace} from '../src/lanes/registry.mjs';import {LaneStore} from '../src/lanes/store.mjs';import {startLaneHttpServer} from '../src/lanes/service.mjs';
import {laneConfig,LANE_CLIENTS} from '../src/lanes/clients.mjs';import {indexProject,search} from '../src/retrieval.mjs';

function withLane(f,lane,fn){const s=new LaneStore(f.home,'product',lane);try{s.beginOperation();return fn(s);}finally{s.close();}}
const cp={objective:'Work',nextAction:'review',status:'review_needed'};
const runProcess=(entry,args)=>new Promise((resolve,reject)=>{const c=spawn(process.execPath,[fileURLToPath(entry),...args],{stdio:['ignore','pipe','pipe']});let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.once('error',reject);c.once('close',code=>code===0?resolve(JSON.parse(out)):reject(new Error(err)));});

test('lanes bind different linked worktrees to the same logical project',t=>{const f=laneFixture(t);const all=f.registry.list('product');assert.equal(all.length,2);assert.notEqual(all[0].root,all[1].root);assert.equal(all[0].common_root,all[1].common_root);});
test('registration is idempotent and does not execute repository hooks',t=>{const f=laneFixture(t);const marker=path.join(f.root,'executed');git(f.primary,'config','core.fsmonitor','sh -c "touch '+marker+'"');const r=f.registry.register(f.authority,'product','alpha',f.alpha);assert(r.duplicate);assert(!fs.existsSync(marker));});
test('primary checkout cannot serve as an isolated lane',t=>{const f=laneFixture(t,{register:false});assert.throws(()=>f.registry.register(f.authority,'product','main',f.primary),{code:'OVERLAPPING_WORKSPACE'});});
test('an independent clone is not granted shared project memory by matching origin/name',t=>{const f=laneFixture(t,{register:false}),other=path.join(f.root,'other');git(f.primary,'clone','-q','--no-hardlinks',f.primary,other);assert.throws(()=>f.registry.register(f.authority,'product','other',other),{code:'UNRELATED_WORKSPACE'});});
test('a subdirectory does not count as another worktree',t=>{const f=laneFixture(t,{register:false}),sub=path.join(f.alpha,'sub');fs.mkdirSync(sub);assert.throws(()=>f.registry.register(f.authority,'product','sub',sub),{code:'WORKSPACE_MUST_BE_REPOSITORY_ROOT'});});
test('a third active lane is refused with the default cooperative MEDIUM limit',t=>{const f=laneFixture(t),third=path.join(f.root,'third');git(f.primary,'worktree','add','-q','-b','feat-three',third,'HEAD');assert.throws(()=>f.registry.register(f.authority,'product','three',third),{code:'LANE_CAPACITY'});});
test('a root cannot be registered under a different lane id',t=>{const f=laneFixture(t,{register:false});f.registry.register(f.authority,'product','alpha',f.alpha);assert.throws(()=>f.registry.register(f.authority,'product','other',f.alpha),{code:'WORKSPACE_ALREADY_REGISTERED'});});
test('retirement does not delete user files and ids are never silently recycled',t=>{const f=laneFixture(t),a=f.registry.active('product','alpha');const r=f.registry.retire('product','alpha',a.epoch);assert.equal(r.filesRemoved,false);assert(fs.existsSync(path.join(f.alpha,'feature.ts')));assert.throws(()=>f.registry.register(f.authority,'product','alpha',f.alpha),{code:'LANE_CLOSED'});});
test('context indices for identical relative paths remain independent',t=>{const f=laneFixture(t);for(const lane of ['alpha','beta'])withLane(f,lane,s=>{indexProject(s,'product');const found=search(s,'product','workspaceMarker',10);assert(found.items[0].body.includes(lane==='alpha'?'ALPHA_MARKER':'BETA_MARKER'));assert(!found.items[0].body.includes(lane==='alpha'?'BETA_MARKER':'ALPHA_MARKER'));});});
test('approved memory is read from the authority, not copied into lane databases',t=>{const f=laneFixture(t);const m=f.authority.proposeMemory('product','Never bypass authorization','ADR');f.authority.reviewMemory('product',m.id,'approved',1);for(const lane of ['alpha','beta'])withLane(f,lane,s=>{assert.equal(s.approvedMemoryCount('product'),1);const memories=s.memories('product',true);assert.equal(memories.length,1);assert.equal(memories[0].id,m.id);assert.equal(s.db.prepare('SELECT count(*) AS n FROM memories').get().n,0);});});
test('proposal in alpha is shared but does not become approved in beta',t=>{const f=laneFixture(t);const p=withLane(f,'alpha',s=>s.proposeMemory('product','Proposed shared architecture','ADR'));withLane(f,'beta',s=>assert.equal(s.approvedMemoryCount('product'),0));assert.equal(f.authority.memories('product').find(m=>m.id===p.id).status,'proposed');});
test('new operation observes revocation made after a previous operation',t=>{const f=laneFixture(t),m=f.authority.proposeMemory('product','GLOBAL_REQUIREMENT','ADR');f.authority.reviewMemory('product',m.id,'approved',1);withLane(f,'alpha',s=>{assert.equal(s.memories('product',true).length,1);f.authority.reviewMemory('product',m.id,'revoked',2);s.endOperation();s.beginOperation();assert.equal(s.memories('product',true).length,0);});});
test('shared memory changing between capture and publication refuses context',t=>{const f=laneFixture(t),m=f.authority.proposeMemory('product','GLOBAL_REQUIREMENT','ADR');f.authority.reviewMemory('product',m.id,'approved',1);withLane(f,'alpha',s=>{s.approvedMemoryCount('product');f.authority.reviewMemory('product',m.id,'revoked',2);assert.throws(()=>s.commitContextEvent('product',{packId:'with-stale-memory'}),{code:'SHARED_MEMORY_CHANGED'});assert.equal(s.events('product').filter(e=>e.type==='context.compiled').length,0);});});
test('closing lane denies future context publication in an existing process',t=>{const f=laneFixture(t);withLane(f,'alpha',s=>{s.approvedMemoryCount('product');f.registry.retire('product','alpha',s.binding.epoch);assert.throws(()=>s.commitContextEvent('product',{packId:'no'}),{code:'LANE_NOT_ACTIVE'});});});
test('checkpoints with the same task id and idempotency key do not overwrite other lane',t=>{const f=laneFixture(t);for(const lane of ['alpha','beta'])withLane(f,lane,s=>{indexProject(s,'product');s.checkpoint('product','TASK',{...cp,objective:lane},0,'key');});for(const lane of ['alpha','beta'])withLane(f,lane,s=>assert.equal(s.task('product','TASK').content.objective,lane));assert.equal(f.authority.task('product','TASK'),null);});
test('same lane preserves CAS and idempotent retry across connections',t=>{const f=laneFixture(t);let result;withLane(f,'alpha',s=>{indexProject(s,'product');result=s.checkpoint('product','TASK',cp,0,'key');});withLane(f,'alpha',s=>{assert.deepEqual(s.checkpoint('product','TASK',cp,0,'key'),result);assert.throws(()=>s.checkpoint('product','TASK',cp,0,'another'),{code:'VERSION_CONFLICT'});});});
test('two actual processes write concurrent lane checkpoints and shared proposals',async t=>{const f=laneFixture(t);const results=await Promise.all(['alpha','beta'].map(lane=>runProcess(new URL('./fixtures/lane-checkpoint-process.mjs',import.meta.url),[f.home,lane])));assert.deepEqual(results.map(r=>r.checkpoint.content.objective).sort(),['alpha','beta']);assert.equal(f.authority.memories('product').length,2);for(const r of results)assert.equal(r.checkpoint.version,1);});
test('scope cannot be changed through domain project argument',t=>{const f=laneFixture(t);withLane(f,'alpha',s=>{assert.throws(()=>s.memories('foreign',true),{code:'LANE_PROJECT_FORBIDDEN'});assert.throws(()=>s.project('foreign'),{code:'LANE_PROJECT_FORBIDDEN'});});});
test('registry schema from a future version is refused',t=>{const f=laneFixture(t);f.registry.db.exec('PRAGMA user_version=99');assert.throws(()=>new LaneRegistry(f.home),{code:'LANE_SCHEMA_VERSION'});});
test('service startup reserves a name before binding and refuses duplicate without killing owner',async t=>{const f=laneFixture(t);const a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end('A')});try{await assert.rejects(startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end('B')}),{code:'SERVICE_OUTCOME_UNKNOWN_OR_ACTIVE'});assert.equal(await(await fetch(a.url)).text(),'A');}finally{await a.close();}});
test('kernel chooses distinct loopback ports; closing A does not close B',async t=>{const f=laneFixture(t);const a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end('A')});const b=await startLaneHttpServer(f.registry,{project:'product',lane:'beta',name:'web',handler:(_,r)=>r.end('B')});try{assert.notEqual(a.url,b.url);assert.equal(a.server.address().address,'127.0.0.1');assert.equal(await(await fetch(a.url)).text(),'A');await a.close();assert.equal(await(await fetch(b.url)).text(),'B');await a.close();}finally{await a.close();await b.close();}});
test('observed active service prevents claiming complete retirement',async t=>{const f=laneFixture(t),a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end()});try{assert.throws(()=>f.registry.retire('product','alpha',f.registry.active('product','alpha').epoch),{code:'LANE_HAS_OBSERVED_SERVICES'});}finally{await a.close();}});
test('old service generation cannot close the next service record',async t=>{const f=laneFixture(t),a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end()});await a.close();const b=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end('B')});try{assert.equal(f.registry.releaseService('product','alpha','web',a.generation),false);assert.equal(await(await fetch(b.url)).text(),'B');}finally{await b.close();}});
test('host and origin are validated before calling application handler',async t=>{const f=laneFixture(t);let called=0;const a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>{called++;r.end();}});try{const status=await new Promise((resolve,reject)=>{http.get(a.url,{headers:{Host:'outside.example'}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));}).on('error',reject);});assert.equal(status,403);assert.equal((await fetch(a.url,{headers:{Origin:'https://outside.example'}})).status,403);assert.equal(called,0);}finally{await a.close();}});
test('closing service owns and closes only its live sockets',async t=>{const f=laneFixture(t);const a=await startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:()=>{}});const socket=net.connect(new URL(a.url).port,'127.0.0.1');try{await once(socket,'connect');const closed=once(socket,'close');await a.close();await closed;assert.equal(f.registry.services('product','alpha')[0].status,'closed');}finally{socket.destroy();await a.close();}});
test('two service processes survive independently and stop using owned lifecycle',async t=>{
 const f=laneFixture(t),children=[];
 const boot=lane=>new Promise((resolve,reject)=>{const c=fork(fileURLToPath(new URL('./fixtures/lane-service-process.mjs',import.meta.url)),[f.home,lane],{stdio:['ignore','pipe','pipe','ipc']});children.push(c);let err='';c.stderr.on('data',d=>err+=d);c.once('error',reject);c.once('message',m=>resolve({c,m}));c.once('exit',code=>{if(code)reject(new Error(err));});});
 try{const [a,b]=await Promise.all(['alpha','beta'].map(boot));assert.notEqual(a.m.url,b.m.url);assert.equal((await(await fetch(a.m.url)).json()).lane,'alpha');const exit=once(a.c,'exit');a.c.send({op:'stop'});await exit;assert.equal((await(await fetch(b.m.url)).json()).lane,'beta');const exitB=once(b.c,'exit');b.c.disconnect();await exitB;}finally{for(const c of children)if(c.exitCode===null&&!c.killed)c.kill();}
});
for(const client of LANE_CLIENTS)test('configuration fragment is host-bound and non-mutating: '+client,t=>{const f=laneFixture(t);const b=f.registry.active('product','alpha');const r=laneConfig(client,{node:process.execPath,entry:fileURLToPath(new URL('../scripts/lanes.mjs',import.meta.url)),home:f.home,binding:b});const raw=typeof r.fragment==='string'?r.fragment:JSON.stringify(r.fragment);assert(raw.includes('alpha'));assert(raw.includes('BBRAINX_HOME'));assert.equal(r.writesConfiguration,false);assert.equal(r.clientVersionVerified,null);assert.equal(r.workspace,b.root);});

test('current authority schema opens for lane reader while another connection holds writer',t=>{
 const f=laneFixture(t);f.authority.db.exec('BEGIN IMMEDIATE');let s;
 try{s=new LaneStore(f.home,'product','alpha');s.beginOperation();assert.equal(s.approvedMemoryCount('product'),0);}
 finally{s?.close();f.authority.db.exec('ROLLBACK');}
});
test('abrupt service death does not authorize PID-based recovery or fake successful cleanup',async t=>{
 const f=laneFixture(t);const c=fork(fileURLToPath(new URL('./fixtures/lane-service-process.mjs',import.meta.url)),[f.home,'alpha'],{stdio:['ignore','pipe','pipe','ipc']});
 c.stdout.resume();c.stderr.resume();
 try{
  const [ready]=await once(c,'message');assert.equal(ready.type,'ready');assert.equal((await fetch(ready.url)).status,200);
  const exited=once(c,'exit');c.kill('SIGKILL');await exited;
  const recorded=f.registry.services('product','alpha')[0];assert.equal(recorded.status,'listening');assert.equal(recorded.liveness,'not-verified');assert.equal(recorded.pidIsSignalAuthority,false);
  await assert.rejects(startLaneHttpServer(f.registry,{project:'product',lane:'alpha',name:'web',handler:(_,r)=>r.end()}),{code:'SERVICE_OUTCOME_UNKNOWN_OR_ACTIVE'});
  assert.throws(()=>f.registry.retire('product','alpha',f.registry.active('product','alpha').epoch),{code:'LANE_HAS_OBSERVED_SERVICES'});
 }finally{if(c.exitCode===null&&!c.killed)c.kill();}
});
test('unqualified memory method queries retrieve both real declarations without dropping the authority',t=>{
 const f=laneFixture(t),repo=fileURLToPath(new URL('../',import.meta.url)),store=new BrainStore(path.join(f.root,'search-state'));
 try{
  store.register('self',repo);indexProject(store,'self');
  for(const name of ['reviewMemory','proposeMemory']){
   const candidates=search(store,'self',name,10).items;
   const firstThree=new Set(candidates.slice(0,3).map(x=>x.path));
   assert(firstThree.has('src/store.mjs'),'Original authority must remain discoverable');
   assert(firstThree.has('src/lanes/store.mjs'),'Lane override must also be discoverable');
   for(const path of ['src/store.mjs','src/lanes/store.mjs'])assert(candidates.some(x=>x.path===path&&x.declares),'Both results must be actual declarations');
  }
 }finally{store.close();}
});
