import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {UsageStore,readUsage,USAGE_DB} from '../src/usage/store.mjs';import {call,pair} from './fixtures/usage-fixtures.mjs';
const setup=t=>{const home=fs.mkdtempSync(path.join(os.tmpdir(),'bbrainx-usage-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));return home;};
function opened(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'bbrainx-usage-')),s=new UsageStore(home);t.after(()=>{s.close();fs.rmSync(home,{recursive:true,force:true});});return s;}
test('Banco opcional ausente não é criado por leitura',t=>{const home=setup(t);assert.deepEqual(readUsage(home,'A').records,[]);assert.equal(fs.existsSync(path.join(home,USAGE_DB)),false);});
test('Importação sobrevive à troca de processo/conexão e não altera brain.sqlite',t=>{const home=setup(t);let s=new UsageStore(home);s.import('A',[{expectedVersion:0,call:call()}]);s.close();s=new UsageStore(home,{readOnly:true});assert.equal(s.snapshot('A').records[0].tokens.totalTokens,1200);s.close();assert.equal(fs.existsSync(path.join(home,'brain.sqlite')),false);});
test('Reimportar o mesmo recibo não duplica tokens',t=>{const s=opened(t),e={expectedVersion:0,call:call()};assert.equal(s.import('A',[e])[0].duplicate,false);assert.equal(s.import('A',[e])[0].duplicate,true);assert.equal(s.snapshot('A').records.length,1);});
test('Correção exige revisão esperada, conserva história e substitui subtotal',t=>{const s=opened(t);s.import('A',[{expectedVersion:0,call:call({usage:null})}]);assert.throws(()=>s.import('A',[{expectedVersion:0,call:call()}]),{code:'USAGE_VERSION_CONFLICT'});s.import('A',[{expectedVersion:1,call:call()}]);assert.equal(s.snapshot('A').records[0].revision,2);assert.equal(s.db.prepare('SELECT count(*) AS n FROM usage_history').get().n,2);});
test('Identidade da chamada não pode migrar para outra tarefa numa correção',t=>{const s=opened(t);s.import('A',[{expectedVersion:0,call:call()}]);assert.throws(()=>s.import('A',[{expectedVersion:1,call:call({task:'other'})}]),{code:'IMMUTABLE_CALL_IDENTITY'});});
test('Um conflito reverte a importação inteira',t=>{const s=opened(t);s.import('A',[{expectedVersion:0,call:call()}]);assert.throws(()=>s.import('A',[{expectedVersion:0,call:call({callId:'new'})},{expectedVersion:0,call:call({usage:null})}]));assert.equal(s.snapshot('A').records.length,1);});
test('Partição lógica de registros usa projeto do host, não do recibo',t=>{const s=opened(t);s.import('A',[{expectedVersion:0,call:call()}]);assert.equal(s.snapshot('B').records.length,0);assert.throws(()=>s.import('A',[{expectedVersion:0,call:{...call(),project:'B'}}]));});
test('Batch não pode repetir a mesma chave',t=>{const s=opened(t),e={expectedVersion:0,call:call()};assert.throws(()=>s.import('A',[e,e]),{code:'DUPLICATE_BATCH_KEY'});});
test('Par é versionado por ID imutável e computado com recibos correntes',t=>{const s=opened(t);s.recordPair('A',pair());assert.equal(s.recordPair('A',pair()).duplicate,true);assert.throws(()=>s.recordPair('A',pair({candidateAccepted:false})),{code:'PAIR_IDENTITY_CONFLICT'});assert.equal(s.snapshot('A').pairs[0].comparable,false);});
test('Schema futuro ou adulterado não é reinicializado',t=>{const home=setup(t),s=new UsageStore(home);s.db.exec('PRAGMA user_version=9');s.close();assert.throws(()=>new UsageStore(home),{code:'USAGE_SCHEMA_VERSION'});});
test('Dois processos importando a mesma chamada produzem um único head',async t=>{const home=setup(t);const init=new UsageStore(home);init.close();const worker=new URL('./fixtures/usage-process.mjs',import.meta.url);const run=()=>new Promise((resolve,reject)=>{const c=spawn(process.execPath,[fileURLToPath(worker),home],{stdio:['ignore','pipe','pipe']});let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.on('error',reject);c.on('close',code=>code===0?resolve(JSON.parse(out)):reject(new Error(err)));});const results=await Promise.all([run(),run()]);assert.equal(results.filter(x=>x[0].duplicate).length,1);assert.equal(readUsage(home,'A').records.length,1);});
