import React from 'react';
import {AbsoluteFill,Composition,Sequence,interpolate,registerRoot,useCurrentFrame,useVideoConfig,spring} from 'remotion';
const ink='#0a141a',mint='#b6efb9',aqua='#63d5b9',muted='#9bb2bc';
const font='Arial, Helvetica, sans-serif';
function Mark({size=90}){return <svg width={size} height={size} viewBox="0 0 64 64" fill="none"><path d="M13 8h20l16 12-18 12 18 12-16 12H13V8Z" stroke={mint} strokeWidth="4" strokeLinejoin="round"/><path d="M14 32h17M31 32 52 9M31 32l21 23" stroke={mint} strokeWidth="4" strokeLinecap="round"/></svg>;}
function Frame({eyebrow,children}){return <AbsoluteFill style={{background:ink,color:'#e9f0ef',fontFamily:font,padding:76}}><div style={{position:'absolute',inset:0,backgroundImage:'radial-gradient(#254039 1px, transparent 1px)',backgroundSize:'25px 25px',opacity:.65}}/><div style={{position:'relative',display:'flex',alignItems:'center',gap:20}}><Mark size={44}/><span style={{fontSize:16,letterSpacing:4,color:muted}}>B B R A I N X / GODMODCODE</span></div><div style={{position:'relative',marginTop:50,fontSize:14,letterSpacing:4,color:aqua}}>{eyebrow}</div>{children}<div style={{position:'absolute',bottom:48,left:78,right:78,display:'flex',justifyContent:'space-between',fontSize:14,color:muted}}><span>Local-first · Open source core · macOS first</span><span>por AB · github.com/oalexandrebelo/BBrainX</span></div></AbsoluteFill>;}
function Intro(){const frame=useCurrentFrame();const {fps}=useVideoConfig();const show=spring({frame,fps,config:{damping:180}});return <Frame eyebrow="CONTEXTO NÃO PRECISA RECOMEÇAR."><div style={{position:'relative',opacity:show,transform:`translateY(${(1-show)*30}px)`,marginTop:45}}><div style={{fontSize:88,lineHeight:1.02,letterSpacing:-5}}>Uma memória.<br/><span style={{color:mint}}>Vários agentes.</span></div><p style={{fontSize:23,color:muted,marginTop:35}}>Continue o trabalho. Preserve as evidências.</p></div></Frame>;}
function Flow(){const frame=useCurrentFrame();const steps=[['SEU HARNESS','Codex · Claude · MCP'],['BBRAINX','Escopo + contexto'],['ESTADO LOCAL','Fontes + checkpoints']];return <Frame eyebrow="O FLUXO, SEM CAIXA-PRETA."><div style={{display:'flex',position:'relative',gap:36,marginTop:90}}>{steps.map(([title,caption],i)=>{const opacity=interpolate(frame,[i*16,i*16+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div key={title} style={{flex:1,opacity,background:'#14252c',border:'1px solid '+(i===1?mint:'#39524f'),borderRadius:14,padding:31,height:180}}><div style={{color:mint,fontSize:15,letterSpacing:2}}>0{i+1}</div><h2 style={{fontSize:24,letterSpacing:-.5,marginTop:27}}>{title}</h2><p style={{color:muted,fontSize:17}}>{caption}</p></div>;})}</div><p style={{position:'relative',fontSize:25,color:muted,marginTop:45}}>Não troca suas credenciais. Não executa shell arbitrário.</p></Frame>;}
function Outro(){const frame=useCurrentFrame();const opacity=interpolate(frame,[0,25],[0,1],{extrapolateRight:'clamp'});return <Frame eyebrow="INSPECIONE. TESTE. CONTRIBUA."><div style={{position:'relative',marginTop:60,opacity}}><h1 style={{fontSize:85,fontWeight:500,letterSpacing:-5,margin:0}}>Evidência antes<br/>de <span style={{color:mint}}>automação.</span></h1><div style={{display:'inline-block',marginTop:35,padding:'16px 25px',border:'1px solid #678578',borderRadius:6,color:mint,fontSize:20}}>BBrainX — GODMODCODE / 0.2</div><p style={{fontSize:17,color:muted}}>Não há promessa de economia sem benchmark. Há código para verificar.</p></div></Frame>;}
function Film(){return <AbsoluteFill><Sequence durationInFrames={180}><Intro/></Sequence><Sequence from={180} durationInFrames={180}><Flow/></Sequence><Sequence from={360} durationInFrames={180}><Outro/></Sequence></AbsoluteFill>;}
registerRoot(()=> <Composition id="BBrainX" component={Film} width={1280} height={720} fps={30} durationInFrames={540}/>);
