export const references={
 invokta:{label:'Invokta · modelo do motor de capacidades',url:'https://docs.invokta.dev/reference/core/'},
 mcp:{label:'MCP · versões e compatibilidade (2026-07-28)',url:'https://modelcontextprotocol.io/specification/2026-07-28/basic/versioning'},
 akita:{label:'Akita · memória para agentes',url:'https://akitaonrails.com/2026/05/23/criei-sistema-memoria-agentes-codigo-ai-memory/'},
 clean:{label:'Akita · código pesquisável para agentes',url:'https://akitaonrails.com/2026/04/20/clean-code-para-agentes-de-ia/'},
 swe:{label:'SWE-agent · interface agente-computador',url:'https://arxiv.org/abs/2405.15793'},
 lost:{label:'Lost in the Middle · seleção de contexto',url:'https://arxiv.org/abs/2307.03172'},
 memgpt:{label:'MemGPT · hierarquia de memória',url:'https://arxiv.org/abs/2310.08560'},
 lingua:{label:'LLMLingua-2 · compressão extrativa',url:'https://arxiv.org/abs/2403.12968'},
 sqlite:{label:'SQLite · WAL e durabilidade',url:'https://sqlite.org/wal.html'},
 laya:{label:'Laya · decisões tipadas',url:'https://github.com/NandhaKishorM/laya'},
 rag:{label:'LightRAG · recuperação documental',url:'https://github.com/HKUDS/LightRAG'},
 flow:{label:'React Flow · interface de grafos',url:'https://reactflow.dev/learn'}
};
export const architecture=[
 {id:'harness',label:'Seu harness',subtitle:'Claude · Codex · Cursor · VS Code',layer:'INTERFACE',status:'protocol',position:{x:0,y:0},icon:'⌘',why:'O agente continua no cliente que você escolheu. O BBrainX entrega evidências e checkpoints por MCP, nas duas eras do protocolo: a corrente, sem handshake, e as anteriores.',input:'Pedido de tarefa num cliente MCP.',output:'Uma chamada tipada, presa ao projeto registrado.',invariant:'Não reconfigurar provedores, tokens, TLS ou gateways do cliente. Os comandos só imprimem a configuração.',tradeoff:'O protocolo é testado com o cliente oficial; cada versão de cada IDE ainda pede homologação própria.',code:'src/mcp.mjs',tests:'test/mcp-wire.test.mjs',refs:['mcp','swe']},
 {id:'scope',label:'Escopo & pré-condições',subtitle:'Acesso antes da busca',layer:'CONTROLE',status:'implemented',position:{x:290,y:0},icon:'◇',why:'Uma consulta semelhante não autoriza recuperar informação de outro projeto. O host define a allowlist; o modelo não concede privilégios a si mesmo.',input:'Identidade local e projeto fixado no lançamento.',output:'Pedido permitido ou recusa explícita.',invariant:'Deny by default. MCP não registra novas raízes nem aprova memórias.',tradeoff:'A fronteira é o usuário local do SO. Não é um serviço multiusuário exposto à rede.',code:'src/engine.mjs',tests:'test/domain.test.mjs',refs:['invokta']},
 {id:'kernel',label:'Motor de capacidades',subtitle:'6 capacidades · um contrato',layer:'AÇÕES',status:'implemented',position:{x:580,y:0},icon:'↯',why:'A mesma regra vale para o CLI, o painel e o MCP. O motor é próprio desde a 0.4: valida entrada e saída, aplica a regra de acesso e o prazo, e devolve erro de código estável. O contrato segue o modelo do Invokta.',input:'Esquemas, identidade do host e argumentos.',output:'Resultado JSON validado, recusa do domínio ou erro controlado.',invariant:'Chamada cancelada não começa. Erro inesperado não vaza mensagem interna.',tradeoff:'Trabalho síncrono (a indexação) não é interrompido pelo prazo. O motor não é memória, banco, executor de shell nem roteador de modelos.',code:'src/capability.mjs',tests:'test/engine.test.mjs',refs:['invokta','swe']},
 {id:'index',label:'Indexação incremental',subtitle:'Hash · arquivos alterados',layer:'RECUPERAÇÃO',status:'implemented',position:{x:0,y:200},icon:'⌁',why:'Reprocessar todo o repositório em cada inicialização desperdiça trabalho. Arquivos inalterados mantêm os chunks; renomes e remoções atualizam as ocorrências.',input:'Raiz explicitamente registrada, arquivos textuais elegíveis.',output:'Snapshot do escopo textual + ocorrências e chunks.',invariant:'Não seguir symlinks; excluir segredos conhecidos; limites de bytes e arquivos.',tradeoff:'Indexação explícita, não watcher contínuo. A heurística de segredos não substitui auditoria. LSP ainda não implementado.',code:'src/retrieval.mjs',tests:'test/domain.test.mjs',refs:['akita','clean']},
 {id:'search',label:'Busca em dois estágios',subtitle:'FTS5 · pt → en · sem LLM',layer:'RECUPERAÇÃO',status:'implemented',position:{x:290,y:200},icon:'⌕',why:'Termos exatos primeiro; depois radicais e um glossário português → inglês, com metade do peso. A declaração de um nome vem antes dos usos e dos testes.',input:'Consulta e projeto autorizado.',output:'Trechos ordenados, com caminho, linhas e hash.',invariant:'Semelhança nunca vence escopo. Estar entre os primeiros não prova cobertura completa.',tradeoff:'Sinônimo fora do glossário continua sem casar. Em 79 perguntas cegas, o arquivo certo ficou entre os 10 primeiros em 84 % das vezes e em 1.º em 46 %.',code:'src/retrieval.mjs',tests:'test/godmode.test.mjs',refs:['akita','swe']},
 {id:'context',label:'Compilador de contexto',subtitle:'Menos entrada. Mais evidência.',layer:'CONTEXTO',status:'implemented',position:{x:580,y:200},icon:'⊞',why:'O modelo precisa do contexto suficiente, não do banco inteiro. O compilador preserva restrições, prioriza evidências, deduplica trechos e verifica fontes antes de servir.',input:'Objetivo, checkpoint, memórias aprovadas e trechos.',output:'Pacote com orçamento, fontes e contagem o200k_base.',invariant:'Um contrato obrigatório não é cortado para caber. Hash divergente exige reindexação.',tradeoff:'o200k_base mede só este payload. Não equivale ao tokenizer de todo modelo, ao histórico do cliente ou à economia faturada.',code:'src/context.mjs',tests:'test/domain.test.mjs',refs:['lost','memgpt','lingua']},
 {id:'memory',label:'Memória governada',subtitle:'Proposta ≠ aprovação',layer:'MEMÓRIA',status:'implemented',position:{x:0,y:400},icon:'▤',why:'Um erro de um agente não pode virar política de todos. Cada memória tem origem, estado e versão; o agente só propõe.',input:'Afirmação e fonte verificável fornecida pelo usuário/agente.',output:'Candidato, aprovação humana ou revogação.',invariant:'Apenas memórias aprovadas entram no pacote. Aprovação é comando humano separado.',tradeoff:'A fonte é registrada, não automaticamente comprovada. Revisão humana continua necessária.',code:'src/store.mjs',tests:'test/domain.test.mjs',refs:['memgpt','akita']},
 {id:'checkpoint',label:'Handoff versionado',subtitle:'Retome sem copiar a conversa',layer:'CONTINUIDADE',status:'implemented',position:{x:290,y:400},icon:'↗',why:'Objetivo, snapshot, pendência e versão são portáveis. Um segundo cliente pode retomar a tarefa sem reproduzir um transcript privado.',input:'Estado da tarefa, versão esperada e chave de idempotência.',output:'Checkpoint durável, histórico e evento na mesma transação.',invariant:'Escritor atrasado recebe conflito. A mesma chave com conteúdo diferente é recusada.',tradeoff:'Não captura raciocínio oculto. Sem runner de evidências, o produto não oferece status done verificado.',code:'src/store.mjs',tests:'test/mcp.test.mjs',refs:['mcp','sqlite']},
 {id:'store',label:'SQLite + journal',subtitle:'Local · WAL · outbox',layer:'PERSISTÊNCIA',status:'implemented',position:{x:580,y:400},icon:'◫',why:'O modo inicial precisa de uma autoridade local simples, não de um cluster. WAL e transações sustentam checkpoints compartilhados entre processos do mesmo usuário.',input:'Comandos autorizados do domínio.',output:'Estado canônico, histórico, eventos e backup consistente.',invariant:'Nunca sincronizar o banco vivo por iCloud ou filesystem de rede.',tradeoff:'Sem criptografia própria em repouso; depende das proteções do SO. Outbox é persistente, mas não um broker distribuído exactly-once.',code:'src/store.mjs',tests:'test/domain.test.mjs',refs:['sqlite','akita']},
 {id:'laya',label:'Perfil Laya',subtitle:'Instalável · não altera o pacote',layer:'OPCIONAL',status:'experimental',position:{x:0,y:610},icon:'⋈',why:'Modelo local de decisão, instalado só por comando. Medido neste Mac: sem ajuste fino, acerta menos que o caminho lexical nas duas decisões testadas. Por isso responde perguntas e serve à medição, e fica fora do pacote.',input:'Texto delimitado e perguntas de escolha, nota ou sim/não.',output:'Probabilidade por opção, ou o motivo de não ter respondido.',invariant:'Pesos conferidos por SHA-256 antes de carregar. Sem rede, sem shell, sem escrita no banco.',tradeoff:'Cerca de 1,4 GB em disco e 1,8 GB de RAM. Só passa a influir no pacote com um checkpoint ajustado e medido.',code:'src/laya.mjs',tests:'test/godmode.test.mjs',refs:['laya']},
 {id:'lightrag',label:'LightRAG Data Port',subtitle:'Documentos conectados',layer:'OPCIONAL',status:'experimental',position:{x:290,y:610},icon:'⌬',why:'Relações documentais podem ajudar perguntas que a busca textual não resolve. Usar o caminho de dados evita uma resposta intermediária redundante.',input:'Documentação aprovada e escopo autorizado.',output:'Entidades, relações, chunks e referências para o compilador.',invariant:'Um grafo documental não é prova exata de chamadas de código.',tradeoff:'Ingestão, embeddings e keywords têm custo. Serviço e modelos não são instalados nem ativados pelo setup básico.',code:'docs/OPTIONAL_PROFILES.md',tests:'docs/EVALUATION.md',refs:['rag']},
 {id:'execution',label:'Execução do seu agente',subtitle:'Fora do serviço de memória',layer:'LIMITE',status:'protocol',position:{x:580,y:610},icon:'›_',why:'A memória não precisa de shell para ser útil. Codex, Claude Code ou seu executor mantêm suas próprias permissões, revisão e validação.',input:'Pacote explícito e tarefa autorizada no harness.',output:'Mudanças e evidências reais fornecidas pelo executor.',invariant:'Nenhum endpoint BBrainX executa comandos arbitrários do modelo.',tradeoff:'OpenHands, browser automation e captura de tela não fazem parte do núcleo inicial.',code:'docs/SECURITY_MODEL.md',tests:'test/http.test.mjs',refs:['swe']}
];
export const edges=[['harness','scope'],['scope','kernel'],['kernel','index'],['index','search'],['search','context'],['memory','context'],['checkpoint','context'],['checkpoint','store'],['index','store'],['memory','store'],['laya','context'],['lightrag','context'],['context','execution']].map(([source,target],i)=>({id:'edge-'+i,source,target,type:'smoothstep',animated:false,style:{stroke:source==='laya'||source==='lightrag'?'#647783':'#35514e',strokeWidth:1.5,strokeDasharray:source==='laya'||source==='lightrag'?'5 5':undefined}}));
export const walkthrough=['harness','scope','kernel','index','search','memory','checkpoint','context','execution'];
