import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position,useNodesState,useEdgesState} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import './style.css';
import {architecture,edges as edgeData,references,walkthrough} from './architecture.js';
import {situations,tools,measuredOn} from './study-map.js';
import {layoutStudy} from './study-layout.js';

const repo='https://github.com/oalexandrebelo/BBrainX';
function Mark(){return <svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M9 7h12l9 7-10 6 10 6-9 7H9V7Z" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/><path d="M10 20h10M20 20l11-12M20 20l11 12" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>;}
const statusLabel={implemented:'IMPLEMENTADO',experimental:'EXPERIMENTAL',protocol:'INTERFACE'};
function ArchitectureNode({data,selected}){return <div className={'arch-node '+(selected?'selected ':'')+data.status}>
 <Handle type="target" position={Position.Top}/><div className="node-meta"><span>{data.layer}</span><i/></div><div className="node-title"><b aria-hidden="true">{data.icon}</b><strong>{data.label}</strong></div><p>{data.subtitle}</p><Handle type="source" position={Position.Bottom}/></div>;}
const nodeTypes={architecture:ArchitectureNode};
function FlowView(){
 const [selected,setSelected]=useState('context'),[guide,setGuide]=useState(-1);
 const initial=useMemo(()=>architecture.map(x=>({id:x.id,position:x.position,type:'architecture',data:x,selected:x.id==='context'})),[]);
 const [nodes,setNodes,onNodesChange]=useNodesState(initial),[edges,,onEdgesChange]=useEdgesState(edgeData);
 const detail=architecture.find(x=>x.id===selected);
 function select(id){setSelected(id);setNodes(ns=>ns.map(n=>({...n,selected:n.id===id})));}
 function next(){const step=(guide+1)%walkthrough.length;setGuide(step);select(walkthrough[step]);}
 return <section className="architecture-layout"><div className="canvas-panel"><div className="panel-bar"><div><span className="eyebrow">01 / ARQUITETURA INSPECIONÁVEL</span><h2>Uma memória. Vários agentes.</h2></div><button className="button secondary" onClick={next}>{guide<0?'Percorrer fluxo':'Próximo passo '+(guide+1)+'/'+walkthrough.length}<span>↗</span></button></div>
 <div className="canvas" aria-label="Mapa interativo da arquitetura"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={(_,n)=>select(n.id)} fitView fitViewOptions={{padding:0.15}} minZoom={0.35} maxZoom={1.6} nodesConnectable={false} colorMode="dark" proOptions={{hideAttribution:false}}><Background color="#2a383d" gap={22} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor={n=>n.data.status==='experimental'?'#64727a':'#56bfa7'} maskColor="#0a1015aa" pannable zoomable/></ReactFlow></div>
 <div className="canvas-footer"><span><i className="dot"/> Local-first por design</span><span>Linhas tracejadas = componentes opcionais</span><span>O percurso é explicativo, não executa agentes.</span></div></div>
 <aside className="inspector" aria-live="polite"><div className="inspector-top"><span className="eyebrow">POR QUE ESTÁ AQUI</span><span className={'status '+detail.status}>{statusLabel[detail.status]}</span></div><div className="detail-icon">{detail.icon}</div><h2>{detail.label}</h2><p className="description">{detail.why}</p>
 {[['ENTRADA',detail.input],['SAÍDA',detail.output],['INVARIANTE',detail.invariant],['TRADE-OFF',detail.tradeoff]].map(([title,value])=><div className="detail-block" key={title}><h3>{title}</h3><p>{value}</p></div>)}
 <div className="code-links"><a href={repo+'/blob/main/'+detail.code} target="_blank" rel="noreferrer">↗ Código / contrato</a><a href={repo+'/blob/main/'+detail.tests} target="_blank" rel="noreferrer">↗ Testes / avaliação</a></div><h3 className="eyebrow">BASE DO ESTUDO</h3><div className="source-links">{detail.refs.map(id=><a href={references[id].url} target="_blank" rel="noreferrer" key={id}>{references[id].label}<span>↗</span></a>)}</div></aside></section>;
}
const basisLabel={medido:'MEDIDO AQUI',spec:'DOCUMENTO OFICIAL','leitura':'LEITURA DO CÓDIGO','decisão':'DECISÃO DE PROJETO'};
function SituationNode({data}){return <div className={'situation-node '+data.id}><div><strong>{data.label}</strong><span>{data.count}</span></div><p>{data.summary}</p></div>;}
function ToolNode({data,selected}){return <div className={'tool-node '+data.group+(selected?' selected':'')}><strong>{data.name}</strong><span>{data.kind}</span></div>;}
const studyNodeTypes={situation:SituationNode,tool:ToolNode};
function StudyMap(){
 const [selected,setSelected]=useState('search');
 const initial=useMemo(()=>layoutStudy(situations,tools).map(node=>({...node,selected:node.id==='search'})),[]);
 const [nodes,setNodes,onNodesChange]=useNodesState(initial);
 const detail=tools.find(x=>x.id===selected), situation=situations.find(x=>x.id===detail.group);
 function select(id){if(!tools.some(x=>x.id===id))return;setSelected(id);setNodes(ns=>ns.map(n=>({...n,selected:n.id===id})));}
 return <section className="architecture-layout study-map"><div className="canvas-panel"><div className="panel-bar"><div><span className="eyebrow">02 / MAPA DO ESTUDO</span><h2>Cada ferramenta, e por que está onde está.</h2></div><span className="map-count">{tools.length} itens · {situations.length} situações</span></div>
 <div className="canvas" aria-label="Mapa interativo do estudo"><ReactFlow nodes={nodes} edges={[]} nodeTypes={studyNodeTypes} onNodesChange={onNodesChange} onNodeClick={(_,n)=>select(n.id)} fitView fitViewOptions={{padding:0.06}} minZoom={0.2} maxZoom={1.6} nodesConnectable={false} nodesDraggable={false} colorMode="dark" proOptions={{hideAttribution:false}}><Background color="#2a383d" gap={22} size={1}/><Controls showInteractive={false}/></ReactFlow></div>
 <div className="canvas-footer"><span><i className="dot"/> Clique num item para ver o porquê</span><span>Medições: {measuredOn}</span><span>Mesmo conteúdo em docs/STUDY_MAP.md</span></div></div>
 <aside className="inspector" aria-live="polite"><div className="inspector-top"><span className="eyebrow">{situation.label.toUpperCase()}</span><span className={'status basis-'+detail.basis}>{basisLabel[detail.basis]}</span></div><h2>{detail.name}</h2><p className="tool-kind">{detail.kind} · {detail.license}</p><p className="description">{situation.summary}</p>
 {[['O QUE É',detail.what],['POR QUE ESTÁ AQUI',detail.why],['EVIDÊNCIA',detail.evidence],[detail.change?'O QUE MUDARIA O VEREDITO':'PRÓXIMO PASSO',detail.change||detail.next]].map(([title,value])=><div className="detail-block" key={title}><h3>{title}</h3><p>{value}</p></div>)}
 {detail.activate?<div className="detail-block"><h3>COMO ATIVAR</h3><code className="activate">{detail.activate}</code></div>:null}
 <div className="source-links"><a href={detail.url} target="_blank" rel="noreferrer">Fonte ↗</a><a href={repo+'/blob/main/docs/STUDY_MAP.md'} target="_blank" rel="noreferrer">Dossiê completo ↗</a></div></aside></section>;
}
function Workbench({boot,refresh}){
 const [project,setProject]=useState(boot?.projects[0]?.id||''),[query,setQuery]=useState('autenticação sessão'),[budget,setBudget]=useState(4000),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[state,setState]=useState(null),[copied,setCopied]=useState(false);
 useEffect(()=>{if(!project&&boot?.projects[0])setProject(boot.projects[0].id);},[boot]);
 useEffect(()=>{if(project)fetch('/api/project?project='+encodeURIComponent(project)).then(r=>r.json()).then(setState).catch(()=>{});},[project,result]);
 async function invoke(action,args){setBusy(true);setError('');setCopied(false);try{const response=await fetch('/api/invoke',{method:'POST',headers:{'content-type':'application/json','x-bbrainx-csrf':boot.csrf},body:JSON.stringify({action,args:{project,...args}})});const json=await response.json();if(!response.ok||!json.ok)throw new Error(json.error||'Falha na operação');setResult(json.data);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function checkpoint(){const old=state?.tasks.find(x=>x.id==='workbench');await invoke('session.checkpoint',{task:'workbench',expectedVersion:old?.version||0,idempotencyKey:crypto.randomUUID(),content:{objective:query,nextAction:'Revisar as fontes selecionadas no harness escolhido.',snapshot:boot.projects.find(x=>x.id===project)?.snapshot,status:'review_needed'}});}
 return <section className="workbench"><div className="work-controls"><span className="eyebrow">03 / LABORATÓRIO LOCAL</span><h2>Traga contexto.<br/><em>Não ruído.</em></h2><p className="muted">Operações reais no seu índice local. Nenhuma chamada a LLM é necessária.</p>
 {!boot?.projects.length?<div className="callout">Nenhum projeto registrado. No terminal, execute <code>npm run demo</code> ou registre uma raiz com <code>bbrainx init</code>. Depois atualize o painel.</div>:null}
 <label>PROJETO<select value={project} onChange={e=>{setProject(e.target.value);setResult(null);}}>{boot?.projects.map(x=><option key={x.id} value={x.id}>{x.id} · {x.fileCount} arquivos</option>)}</select></label>
 <label>O QUE VOCÊ PRECISA ENTENDER?<textarea value={query} onChange={e=>setQuery(e.target.value)} rows={4} placeholder="Ex.: como funciona a validação de sessão?"/></label>
 <label>ORÇAMENTO DO PACOTE <span>{budget.toLocaleString('pt-BR')} tokens</span><input aria-label="Orçamento do pacote" type="range" min="512" max="8000" step="128" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label>
 <button className="button primary" disabled={!project||busy||!query.trim()} onClick={()=>invoke('context.bootstrap',{query,budget})}>{busy?'Processando…':'Compilar contexto'}<span>↗</span></button>
 <div className="button-pair"><button className="button secondary" disabled={!project||busy} onClick={()=>invoke('context.index',{})}>Reindexar</button><button className="button secondary" disabled={!project||busy||!query.trim()} onClick={()=>invoke('context.search',{query,limit:12})}>Buscar</button></div>
 <button className="text-button" disabled={!project||busy||!state?.project.snapshot} onClick={checkpoint}>Salvar checkpoint de revisão →</button>
 <div className="metric-note">A contagem usa <strong>o200k_base</strong> para este payload. Uso total do harness, cache do provedor e economia financeira permanecem desconhecidos.</div></div>
 <div className="work-output"><div className="panel-bar"><div><span className="eyebrow">EVIDÊNCIA / RESULTADO</span><h2>{result?.packId?'Pacote pronto para o agente':'Saída verificável'}</h2></div>{result?<button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(result.text||JSON.stringify(result,null,2));setCopied(true);}catch{setError('Não foi possível copiar. Selecione o texto abaixo.');}}}>{copied?'Copiado':'Copiar'}</button>:null}</div>
 {error?<div role="alert" className="error">{error}</div>:null}
 {result?.packId?<div className="result-stats"><div><b>{result.payloadTokens}</b><span>TOKENS DO PAYLOAD</span></div><div><b>{result.sources.length}</b><span>FONTES VERIFICADAS</span></div><div><b>{result.snapshot.slice(0,8)}</b><span>SNAPSHOT TEXTUAL</span></div></div>:null}
 {result?<pre tabIndex={0} className="output-pre">{result.text||JSON.stringify(result,null,2)}</pre>:<div className="empty-output"><div className="empty-symbol">⊞</div><h3>O contexto certo começa com uma pergunta.</h3><p>Busque, selecione e inspecione as fontes.<br/>Nada é enviado a um provedor externo.</p></div>}
 <div className="event-strip"><span className="eyebrow">HISTÓRICO LOCAL</span>{state?.events.slice(-5).reverse().map(event=><div key={event.seq}><span className="dot"/>{event.type}<time>{new Date(event.created).toLocaleTimeString('pt-BR')}</time></div>)}</div></div></section>;
}
function Study(){return <section className="study"><div className="study-hero"><span className="eyebrow">04 / FUNDAMENTOS E LIMITES</span><h2>Engenharia antes<br/>do <em>modo deus.</em></h2><p>GODMODCODE é uma ambição de produto. Não é uma permissão para ignorar segurança, inventar benchmarks ou carregar todas as dependências de uma vez.</p></div><div className="study-grid">{[
 ['01','Aprendizado de campo','Akita: nomes pesquisáveis, testes headless, persistência imediata e memória independente do diretório atual. São relatos de engenharia, não prova científica de desempenho universal.','akita'],
 ['02','Contexto suficiente','Lost in the Middle observa sensibilidade à posição em tarefas específicas. Nossa hipótese: selecionar evidências e preservar restrições é melhor que inflar todo prompt. Precisa de benchmark próprio.','lost'],
 ['03','Interface importa','SWE-agent investiga interfaces desenhadas para agentes. Aplicação: seis capacidades pequenas, erros explícitos e resultados com fontes, sem um endpoint execute-anything.','swe'],
 ['04','Memória em camadas','MemGPT separa memória externa e contexto ativo. Aplicação: dados canônicos fora do prompt, checkpoints portáveis e recuperação seletiva. Não importamos estados internos entre modelos.','memgpt'],
 ['05','Compressão com cuidado','LLMLingua-2 estuda classificação extrativa de tokens em datasets definidos. Nesta versão selecionamos trechos íntegros; não apagamos contratos para atingir uma taxa de compressão.','lingua'],
 ['06','Simplicidade verificável','SQLite e FTS5 dispensam serviços externos no primeiro uso. Modelos, grafos e sandboxes só entram quando um experimento demonstrar utilidade adicional.','sqlite']
 ].map(([number,title,description,source])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p><a target="_blank" rel="noreferrer" href={references[source].url}>Ler fonte primária ↗</a></article>)}</div><a className="button primary dossier-link" target="_blank" rel="noreferrer" href={repo+'/blob/main/docs/DOSSIER.md'}>Abrir dossiê completo no repositório <span>↗</span></a></section>;}
function Integrations({boot}){const clients=[['Claude Code','claude','Imprime o comando claude mcp add e o JSON de .mcp.json.'],['Codex CLI','codex','Imprime o bloco TOML para ~/.codex/config.toml.'],['Cursor','cursor','Imprime o JSON de .cursor/mcp.json.'],['VS Code','vscode','Imprime o JSON de .vscode/mcp.json.'],['Gemini CLI','gemini','Imprime o JSON de ~/.gemini/settings.json.']];
 return <section className="integrations"><span className="eyebrow">05 / INTEGRAÇÃO SEM SURPRESAS</span><h2>Seu agente continua seu.<br/><em>O contexto se conecta.</em></h2><div className="callout">Primeiro, na pasta do projeto: <code>node bin/bbrainx.mjs up --root .</code> — registra, indexa e mostra os próximos passos.</div><div className="integration-grid">{clients.map(([name,id,note])=><article key={id}><span className="client-mark">{name[0]}</span><h3>{name}</h3><p>O servidor fala as duas eras do protocolo MCP. Configurações e credenciais do cliente não são alteradas: o comando só imprime.</p><code>node bin/bbrainx.mjs config --project SEU_ID --client {id}</code><small>{note}</small></article>)}</div><div className="health-card"><div><h3>Diagnóstico do host</h3><p>Para o melhor cenário desta máquina, com o comando de cada passo: <code>node bin/bbrainx.mjs doctor</code>.</p></div><pre>{boot?JSON.stringify(boot.doctor,null,2):'Diagnóstico disponível ao iniciar o servidor local.'}</pre></div></section>;}
function App(){const [tab,setTab]=useState('architecture'),[boot,setBoot]=useState(null),[connection,setConnection]=useState('connecting');async function refresh(){try{const r=await fetch('/api/bootstrap');if(!r.ok)throw new Error();setBoot(await r.json());setConnection('local');}catch{setConnection('offline');}}useEffect(()=>{refresh();},[]);
 return <><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('architecture');}}><Mark/><span>BBrain<span>X</span><small>GODMODCODE / 0.4</small></span></a><nav aria-label="Navegação principal">{[['architecture','Arquitetura'],['map','Mapa do estudo'],['workbench','Laboratório'],['study','Estudo'],['integrations','Conectar']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="header-right"><span className="connection"><i className={'dot '+(connection==='local'?'':'muted-dot')}/>{connection==='local'?'LOCAL RUNTIME':connection==='offline'?'OFFLINE':'CONECTANDO'}</span><a className="github-button" href={repo} target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
 <main><div className="page-intro"><div><span className="eyebrow">CONTEXT OPERATING LAYER</span><h1>Continuidade sem começar do zero<span>.</span></h1></div><p>Local. Inspecionável. Independente do modelo.</p></div>{connection==='offline'?<div className="offline-note">Explorador disponível. Para operações reais, inicie <code>npm start</code> e abra o endereço local informado.</div>:null}
 {tab==='architecture'?<FlowView/>:tab==='map'?<StudyMap/>:tab==='workbench'?<Workbench boot={boot} refresh={refresh}/>:tab==='study'?<Study/>:<Integrations boot={boot}/>}</main>
 <footer><span>BBrainX — evidência antes de automação.</span><div><span>Nenhuma telemetria externa</span><a href="https://www.alexandrebelo.com.br/" target="_blank" rel="noreferrer">por <strong>AB</strong> ↗</a></div></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
