// Mapa do estudo: por que cada ferramenta está na situação em que está. Fonte única do painel e de docs/STUDY_MAP.md
// (gerado por scripts/study-doc.mjs; o teste test/study.test.mjs reprova se os dois divergirem).
// `basis` diz de onde vem a evidência: 'medido' (executado e medido neste projeto), 'spec' (documento oficial lido),
// 'leitura' (código do upstream lido, sem executar) ou 'decisão' (escolha de projeto).

export const measuredOn='4 de outubro de 2026, MacBook M5 Pro, 24 GB, macOS 26, Node 24';

export const situations=[
  {id:'core',label:'Núcleo',summary:'Roda sempre. Sem modelo, sem rede, sem conta.'},
  {id:'profile',label:'Perfil ativável',summary:'Existe e funciona, mas só entra por comando seu.'},
  {id:'technique',label:'Só técnica',summary:'A ideia entrou, reescrita aqui. O projeto não é instalado.'},
  {id:'reference',label:'Referência',summary:'Consultado. Não é copiado para este repositório.'},
  {id:'out',label:'Fora',summary:'Avaliado e recusado, com o motivo e o que mudaria o veredito.'}
];

export const tools=[
  // ── núcleo ──────────────────────────────────────────────────────────────
  {id:'sqlite',group:'core',name:'SQLite + FTS5',kind:'banco e índice',license:'domínio público (embutido no Node)',url:'https://sqlite.org/fts5.html',basis:'medido',
   what:'Um arquivo local guarda projetos, trechos indexados, checkpoints, memórias e eventos. A busca textual é a do próprio SQLite.',
   why:'Dispensa serviço, Docker e conta. Um único processo dá transação de verdade para checkpoint, idempotência e histórico.',
   evidence:'Primeira indexação de 3.662 arquivos em 3 a 4 s (medida da 0.3). Migração de esquema com cópia de segurança coberta por teste.',
   next:'Fatiar a indexação para não bloquear o servidor em repositórios muito grandes.'},
  {id:'engine',group:'core',name:'Motor de capacidades próprio',kind:'contrato das 6 ferramentas',license:'MIT (original; modelo: Invokta 0.9, MIT)',url:'https://github.com/oalexandrebelo/BBrainX/blob/main/src/capability.mjs',basis:'medido',
   what:'Cada capacidade declara entrada, saída, regra de acesso e prazo. O motor valida, autoriza, limita o tempo e devolve erro de código estável.',
   why:'Decisão do dono: ter o motor em casa. O contrato do Invokta foi o modelo; a implementação é nossa e não instala nenhum pacote dele.',
   evidence:'Pacotes de produção no lockfile: 121 → 25. Prazo (TIMEOUT) distinto de cancelamento. Sete defeitos injetados de propósito, todos pegos pelos testes.',
   next:'Saída tipada por capacidade, no lugar do envelope genérico ok/data/error.'},
  {id:'mcp',group:'core',name:'Servidor MCP próprio, duas eras',kind:'protocolo com os harnesses',license:'MIT (original)',url:'https://modelcontextprotocol.io/specification/2026-07-28/basic/versioning',basis:'spec',
   what:'JSON-RPC por stdio. Atende a revisão corrente do protocolo (2026-07-28, sem handshake) e as anteriores (com initialize) no mesmo processo.',
   why:'A revisão corrente tirou o handshake: um servidor só legado deixa de fora o cliente só moderno. Falar as duas eras é o que mantém o «qualquer harness».',
   evidence:'O cliente oficial do protocolo conversa com o servidor nos testes. Onze defeitos injetados, todos pegos, incluindo uma queda real: chamada e cancelamento no mesmo bloco derrubavam o processo.',
   next:'Conferir, harness por harness, qual era cada um fala hoje. Isso ainda não foi medido.'},
  {id:'search',group:'core',name:'Busca em dois estágios, pt → en',kind:'recuperação',license:'MIT (original)',url:'https://github.com/oalexandrebelo/BBrainX/blob/main/src/retrieval.mjs',basis:'medido',
   what:'Primeiro os termos exatos; depois os mesmos termos por radical e por um glossário de programação português → inglês, com metade do peso. Palavras vazias saem da consulta.',
   why:'A pergunta costuma vir em português e o código está em inglês. A 0.3 achava nome de função, mas errava pergunta em linguagem natural.',
   evidence:'79 perguntas cegas, escritas por outro autor sobre dois repositórios de terceiros: arquivo certo entre os 10 primeiros em 54 % → 84 %; em 1.º lugar, 33 % → 46 %. Posição melhorou em 40 casos e piorou em 7.',
   next:'Fatiar por declaração em vez de blocos de 60 linhas; mapa de símbolos.'},
  {id:'pack',group:'core',name:'Pacote de contexto com orçamento',kind:'o que o agente recebe',license:'MIT (original)',url:'https://github.com/oalexandrebelo/BBrainX/blob/main/src/context.mjs',basis:'medido',
   what:'Checkpoint, memórias aprovadas e trechos com caminho, linhas e hash, dentro de um teto de tokens. O que ficou de fora é declarado.',
   why:'O agente precisa do suficiente, não do repositório inteiro. Documentação fica com no máximo metade do orçamento enquanto houver código candidato.',
   evidence:'Arquivo alterado depois da indexação é relido antes de ser servido. Restrição obrigatória nunca é cortada para caber: o pacote é recusado.',
   next:'Prefixo estável, para o cache do provedor aproveitar o começo do pacote.'},
  {id:'runtime-deps',group:'core',name:'Zod, gpt-tokenizer, React Flow',kind:'dependências de execução',license:'MIT',url:'https://github.com/xyflow/xyflow',basis:'decisão',
   what:'Zod valida entrada e saída; gpt-tokenizer conta os tokens do pacote (o200k_base); React Flow desenha o painel e este mapa.',
   why:'São pequenas, maduras e não chamam rede. Reescrevê-las não traria nada.',
   evidence:'Versões fixadas no lockfile; a instalação roda sem scripts de ciclo de vida.',
   next:'Nenhuma troca prevista.'},

  // ── perfil ativável ─────────────────────────────────────────────────────
  {id:'laya',group:'profile',name:'Laya 0.3.26',kind:'modelo local de decisão',license:'Apache-2.0 (código e pesos)',url:'https://github.com/NandhaKishorM/laya',basis:'medido',
   what:'Um codificador com cabeça de decisão: escolhe entre opções, dá nota ou responde sim/não. Não gera texto, por isso é rápido.',
   why:'Foi reativado e medido. Sem ajuste fino ele acerta menos que o caminho lexical nas duas decisões testadas, então fica instalável para perguntar e medir, e não altera o pacote.',
   evidence:'Roda pela GPU do Mac (MPS): carga em 4 a 18 s, 8 ms por par curto, 720 ms para julgar 10 trechos, 1,8 GB de RAM. Como reordenador: acerto em 1.º caiu de 42 % para 6 %. Relevância de memória: 56 % contra 73 % do lexical.',
   activate:'node bin/bbrainx.mjs laya install',
   next:'Ajuste fino com rótulos do próprio uso. O upstream também diz que as bases ficam perto do acaso sem isso.'},
  {id:'remotion',group:'profile',name:'Remotion',kind:'filme de apresentação',license:'licença própria do Remotion (não é MIT)',url:'https://www.remotion.dev/docs/license',basis:'decisão',
   what:'Composição em React que gera o vídeo de apresentação. Vive em media/, com dependências e lockfile separados.',
   why:'Serve à publicação, não ao produto. Por ter licença própria, não pode ser dependência do núcleo.',
   evidence:'A CI renderiza o filme a cada revisão. Os números que aparecem nele são os deste mapa.',
   activate:'cd media && npm ci --ignore-scripts && npm run render',
   next:'Confira a elegibilidade da licença gratuita antes de usar numa empresa.'},
  {id:'mcp-sdk',group:'profile',name:'SDK oficial do MCP',kind:'só no teste de interoperabilidade',license:'MIT (linha 1.x)',url:'https://github.com/modelcontextprotocol/typescript-sdk',basis:'decisão',
   what:'O cliente oficial do protocolo, instalado só como dependência de desenvolvimento.',
   why:'Testar o servidor próprio só com cliente próprio não prova nada. O cliente oficial é a prova de que um harness de verdade conversa com ele.',
   evidence:'Dois clientes oficiais independentes gravam e leem o mesmo checkpoint nos testes.',
   activate:'npm test',
   next:'Acrescentar o cliente da linha 2.x para provar também a era sem handshake com código de terceiros.'},

  // ── só técnica ──────────────────────────────────────────────────────────
  {id:'invokta',group:'technique',name:'Invokta',kind:'motor de capacidades',license:'MIT',url:'https://github.com/vinilana/invokta',basis:'leitura',
   what:'Motor de capacidades tipadas com adaptadores para CLI e MCP.',
   why:'Era dependência até a 0.3. Virou o modelo do motor próprio: ordem entre validação, acesso e prazo, códigos de erro e nomes portáveis de ferramenta.',
   evidence:'O aviso completo da licença MIT acompanha o repositório, porque mensagens e regras foram adaptadas. O Invokta não usa o JEV: conferido nas dependências e no código publicado.',
   next:'Vale acompanhar: composição de capacidades e conectores não foram trazidos.'},
  {id:'laya-contract',group:'technique',name:'Contrato de decisão do Laya',kind:'ideias sem o modelo',license:'Apache-2.0',url:'https://github.com/NandhaKishorM/laya',basis:'leitura',
   what:'Decisão só entre opções fechadas, abstenção explícita e aviso de truncamento.',
   why:'Valem mesmo sem modelo: o pacote declara o que cortou, e qualquer decisão automática precisa poder dizer «não sei».',
   evidence:'O intermediário do perfil nunca lança: prazo, recusa e queda viram motivo, e três falhas seguidas abrem um disjuntor.',
   next:'Usar a abstenção calibrada quando houver um checkpoint ajustado.'},
  {id:'jev-compaction',group:'technique',name:'fast-jev-compaction',kind:'compactação de sessão sobre o JEV',license:'MIT',url:'https://github.com/tamaratran/fast-jev-compaction',basis:'leitura',
   what:'Usa o JEV para decidir o que sai de uma sessão longa. O valor está na política determinística que roda antes e depois do modelo.',
   why:'O que nunca pode ser descartado é regra, não palpite de modelo. Essa parte já vale no pacote; a compactação de sessão em si não foi implementada.',
   evidence:'Segundo a leitura do código e das issues do projeto, a decisão por modelo ficou abaixo de regras triviais e um marcador de «conteúdo removido» foi imitado pelo agente.',
   next:'Compactar sessão com resíduo estruturado, só depois de medir com rótulos.'},
  {id:'jev-ultrafast',group:'technique',name:'jev-ultrafast',kind:'agente de navegador sobre o JEV',license:'MIT',url:'https://github.com/browser-use/jev-ultrafast',basis:'leitura',
   what:'Separa decidir de executar: o modelo rápido escolhe o alvo, o código valida que o alvo ainda existe e só então age.',
   why:'A mesma disciplina já está no núcleo: trecho é conferido contra o arquivo antes de ser servido, e checkpoint só grava na versão esperada.',
   evidence:'Parte dos tempos anunciados pelo projeto não tem arquivo de resultado, segundo a leitura do repositório.',
   next:'Roteamento por regras (qual orçamento, quando compactar) antes de qualquer modelo.'},
  {id:'semif',group:'technique',name:'SemIf-OpenJev',kind:'condicional semântico local',license:'MIT (modelo Qwen: Apache-2.0)',url:'https://github.com/TheoLeeCJ/SemIf-OpenJev',basis:'leitura',
   what:'Não é uma reimplementação do JEV. É um arnês que lê as letras de resposta de um modelo de linguagem congelado, de cerca de 9 GB.',
   why:'A boa ideia é dar erro em vez de truncar a entrada em silêncio. O modelo é pesado demais para um perfil padrão.',
   evidence:'Tem medida em chip M5 no próprio repositório; nada foi medido aqui.',
   next:'Comparar com o Laya no mesmo conjunto rotulado, se um dia houver motivo.'},
  {id:'lightrag',group:'technique',name:'LightRAG',kind:'recuperação por grafo de documentos',license:'MIT',url:'https://github.com/HKUDS/LightRAG',basis:'leitura',
   what:'Extrai entidades e relações dos documentos com um LLM e consulta em dois níveis: nomes específicos e temas.',
   why:'A indexação chama LLM duas vezes por bloco e não entende código: o «grafo de chamadas» seria inferência, não fato. Ficou a ideia dos dois níveis, que aqui são nomes declarados e títulos.',
   evidence:'«Frações de segundo» e «90 % mais barato» não aparecem no código nem na documentação do projeto, segundo a leitura. Não suporta SQLite.',
   next:'Perfil para documentação em prosa, com servidor separado e só o caminho que devolve dados.'},
  {id:'omniroute',group:'technique',name:'OmniRoute',kind:'gateway de modelos',license:'MIT',url:'https://github.com/diegosouzapw/OmniRoute',basis:'leitura',
   what:'Gateway de LLM com roteamento, cotas e compressão.',
   why:'O BBrainX não é gateway. Entraram o formato de handoff do checkpoint e o disjuntor. As funções que imitam a impressão digital de outros clientes contornam termos de serviço e não serão reproduzidas.',
   evidence:'O checkpoint guarda o que foi feito, decisões, arquivos tocados e evidências desde a 0.3.',
   next:'Cliente opcional de um gateway que o usuário já opere.'},
  {id:'plandex',group:'technique',name:'plandex',kind:'agente de programação',license:'MIT',url:'https://github.com/plandex-ai/plandex',basis:'leitura',
   what:'Agente em Go com mapa de símbolos por tree-sitter.',
   why:'Projeto parado e dependente de Docker e chave de LLM. Ficou a ideia de pôr a declaração de um nome antes dos usos.',
   evidence:'Achar a definição de um identificador em 1.º lugar: 38 % → 98 % na 0.3 (300 casos gerados).',
   next:'Símbolos por tree-sitter, como perfil.'},
  {id:'mem0',group:'technique',name:'mem0',kind:'memória para agentes',license:'Apache-2.0',url:'https://github.com/mem0ai/mem0',basis:'leitura',
   what:'Extrai fatos da conversa com um LLM e busca de forma híbrida.',
   why:'Grava memória ativa sem humano e, por padrão, envia dados a um provedor. Aqui a memória é proposta pelo agente e aprovada por você. Ficaram a deduplicação e o filtro por relevância.',
   evidence:'Telemetria ligada por padrão no upstream, segundo a leitura do código. A sincronização com Obsidian citada em dossiês de terceiros não existe nele.',
   next:'Exportar memórias aprovadas em Markdown.'},
  {id:'ecc',group:'technique',name:'ECC',kind:'catálogo de skills e hooks',license:'MIT',url:'https://github.com/affaan-m/ecc',basis:'leitura',
   what:'Coleção grande de skills, agentes e hooks para harnesses.',
   why:'Instalar o pacote inteiro injeta dezenas de milhares de tokens fixos por sessão. Ficou a separação entre o que o host observa e o que o agente declara.',
   evidence:'Commit e ramo do Git são lidos pelo host e carimbados no checkpoint; o agente não consegue forjá-los.',
   next:'Hook de início de sessão que injeta o checkpoint sozinho.'},
  {id:'agy-staff',group:'technique',name:'agy-staff',kind:'delegação entre harnesses',license:'MIT',url:'https://github.com/keli-wen/agy-staff',basis:'leitura',
   what:'Delega trabalho ao CLI Antigravity a partir de outro harness.',
   why:'Exige conta, envia o repositório para fora e não tem teto de custo. A ideia de passar o bastão é a mesma do checkpoint, que aqui fica local.',
   evidence:'Handoff entre dois clientes independentes é testado a cada revisão.',
   next:'Nada previsto.'},
  {id:'akita',group:'technique',name:'Artigos do Akita',kind:'relatos de engenharia',license:'direitos do autor (só citação)',url:'https://akitaonrails.com/',basis:'leitura',
   what:'Série sobre agentes de programação, memória e código pesquisável.',
   why:'Uma das técnicas daqui bate com uma medida dele: no ai-memory, só tirar palavras vazias da consulta levou o acerto entre os 5 primeiros de 0,617 para 0,668.',
   evidence:'O repositório do ai-memory publica 0,617 → 0,668 → 0,823; o artigo cita 0,779. Vale o repositório. O formato OKF de intercâmbio não foi implementado aqui.',
   next:'Importar e exportar memórias num formato aberto, com teste do esquema.'},
  {id:'science',group:'technique',name:'Literatura científica',kind:'método de medição',license:'direitos dos autores (só citação)',url:'https://github.com/oalexandrebelo/BBrainX/blob/main/docs/EVALUATION.md',basis:'leitura',
   what:'Estudos sobre recuperação em código, posição da evidência no contexto e memória de agentes.',
   why:'O que mais mudou o projeto foi o método: intervalo de confiança, comparação pareada, corpus fixado e casos escritos por quem não ajusta o buscador.',
   evidence:'Com 7 casos, «2 de 7» tem intervalo de 8 % a 64 %: não sustenta conclusão. Por isso a avaliação agora informa o intervalo e o snapshot do corpus.',
   next:'Tarefas reais com critério de aceite, que continuam por fazer.'},
  {id:'logo-skill',group:'technique',name:'LOGO-DESIGN-SKILL',kind:'processo de identidade',license:'MIT',url:'https://github.com/KAANKIZILTUG/LOGO-DESIGN-SKILL',basis:'leitura',
   what:'Método para chegar a uma marca simples e legível em tamanho pequeno.',
   why:'Foi usado o processo, não a galeria. As três opções em public/brand/options são geometria original.',
   evidence:'Cada opção é um SVG de menos de 300 bytes, em uma cor.',
   next:'O monograma BX está em uso por escolha do dono, de forma provisória. Falta validar com usuários; nada aqui é parecer de marca.'},

  // ── referência ──────────────────────────────────────────────────────────
  {id:'system-design-101',group:'reference',name:'system-design-101',kind:'guia visual de arquitetura',license:'CC BY-NC-ND 4.0',url:'https://github.com/ByteByteGoHq/system-design-101',basis:'leitura',
   what:'Explicações ilustradas de conceitos de arquitetura.',
   why:'A licença proíbe uso comercial e obra derivada. Não pode entrar num repositório MIT.',
   evidence:'Nenhum texto ou imagem foi copiado.',
   next:'Você pode clonar e registrar como projeto de consulta no seu próprio computador.'},
  {id:'awesome-system-design',group:'reference',name:'awesome-system-design-resources',kind:'lista de estudo',license:'GPL-3.0',url:'https://github.com/ashishps1/awesome-system-design-resources',basis:'leitura',
   what:'Lista de materiais de arquitetura de sistemas.',
   why:'GPL-3.0 obrigaria o repositório inteiro a seguir a mesma licença se o conteúdo fosse incorporado.',
   evidence:'Só o link.',
   next:'Mesma saída: clone local do usuário, indexado como consulta.'},
  {id:'puncsky',group:'reference',name:'system-design-and-architecture',kind:'notas de arquitetura',license:'nenhuma (todos os direitos reservados)',url:'https://github.com/puncsky/system-design-and-architecture',basis:'leitura',
   what:'Notas e resumos de arquitetura.',
   why:'Sem licença, nem redistribuir trecho é garantido.',
   evidence:'Só o link.',
   next:'Nenhuma.'},
  {id:'backend-questions',group:'reference',name:'Back-End-Developer-Interview-Questions',kind:'perguntas de revisão',license:'GPL-2.0',url:'https://github.com/arialdomartini/Back-End-Developer-Interview-Questions',basis:'leitura',
   what:'Perguntas abertas sobre projeto de back-end.',
   why:'Boas para revisar uma arquitetura, mas a licença não permite trazê-las para cá.',
   evidence:'Só o link. Pergunta de entrevista não é critério de aceite.',
   next:'Escrever perguntas de revisão originais, se fizer falta.'},
  {id:'free-for-dev',group:'reference',name:'free-for.dev',kind:'lista de camadas gratuitas',license:'nenhuma declarada',url:'https://free-for.dev/',basis:'leitura',
   what:'Lista de serviços com plano gratuito.',
   why:'O núcleo não exige conta nenhuma, e camada gratuita some sem aviso.',
   evidence:'Só o link.',
   next:'Nenhuma.'},
  {id:'awesome-jev',group:'reference',name:'awesomejev.com',kind:'catálogo de produtos sobre o JEV',license:'catálogo de terceiros',url:'https://awesomejev.com/',basis:'leitura',
   what:'Mais de mil projetos construídos sobre a API do JEV.',
   why:'Serve para achar técnica, não para depender. Dos que tocam contexto e memória, o que se aproveita é método de medição.',
   evidence:'Contagem e triagem feitas pelo estudo; nada dali foi executado.',
   next:'Revisitar se surgir um conjunto público de decisões rotuladas em código.'},

  // ── fora ────────────────────────────────────────────────────────────────
  {id:'jev-api',group:'out',name:'JEV (API hospedada)',kind:'modelo de decisão fechado',license:'serviço proprietário',url:'https://awesomejev.com/',basis:'decisão',
   what:'Serviço pago de decisões tipadas. O Laya fala o mesmo protocolo e roda na sua máquina.',
   why:'O núcleo não envia código nem contexto a serviço de terceiros. Nenhuma linha do BBrainX chama o JEV.',
   evidence:'Limiar de confiança ajustado no JEV não se transfere para o Laya: os dois erram de jeitos diferentes.',
   change:'Nada. Quem quiser usar o JEV faz isso no próprio harness.'},
  {id:'jev-jarvis',group:'out',name:'jev-chat-jarvis',kind:'assistente para Android',license:'MIT',url:'https://github.com/jev-chat/jev-chat-jarvis',basis:'leitura',
   what:'Lê a tela do celular por acessibilidade e OCR e responde conversas.',
   why:'Captura de tela e de conversa não tem lugar num motor de contexto de código. Segundo a leitura do repositório, o padrão envia o chat a um servidor de terceiro.',
   evidence:'Leitura parcial do código; o aplicativo não foi instalado.',
   change:'Nada.'},
  {id:'llamafactory',group:'out',name:'LlamaFactory',kind:'ajuste fino de LLMs',license:'Apache-2.0',url:'https://github.com/hiyouga/LlamaFactory',basis:'leitura',
   what:'Ferramenta para ajustar modelos de linguagem que geram texto.',
   why:'Não treina classificador nem codificador, que é o que o Laya é. E treinar com o código do usuário faz o modelo memorizá-lo.',
   evidence:'O ajuste fino do Laya tem roteiro próprio no repositório dele.',
   change:'Se o projeto passar a ter um modelo gerador próprio, o que não está nos planos.'},
  {id:'needle',group:'out',name:'needle',kind:'modelo minúsculo de chamada de ferramenta',license:'Apache-2.0',url:'https://github.com/cactus-compute/needle',basis:'leitura',
   what:'Modelo pequeno para escolher ferramentas.',
   why:'A versão publicada para vetores não tem a cabeça de embedding treinada nem avaliação de recuperação.',
   evidence:'Leitura do código e do cartão do modelo na 1.ª rodada.',
   change:'Uma avaliação de recuperação em código publicada pelo projeto.'},
  {id:'embeddings',group:'out',name:'Busca vetorial (e5 multilíngue)',kind:'técnica testada',license:'MIT (modelos e5)',url:'https://huggingface.co/intfloat/multilingual-e5-small',basis:'medido',
   what:'Vetores de um modelo multilíngue pequeno, fundidos com a busca textual por posição.',
   why:'Medido antes de construir, e o resultado não fecha. Nas perguntas cegas a fusão subiu o acerto em 1.º lugar, mas melhorou 26 casos e piorou 16, diferença que pode ser acaso; neste repositório ela piorou. Não entrou nesta rodada.',
   evidence:'79 perguntas cegas: em 1.º lugar, 46 % com a busca textual e 56 % com a fusão; entre os 10, 84 % e 85 %. 36 perguntas sobre este repositório: 44 % e 42 % em 1.º; 94 % e 86 % entre os 10. Sozinho, o modelo ficou em 29 % e 22 %.',
   change:'Mais casos cegos e um modelo treinado em código. É o primeiro candidato a perfil: o ambiente do Laya já traz o que ele precisa.'},
  {id:'openhands',group:'out',name:'OpenHands',kind:'executor em sandbox',license:'MIT (pasta enterprise à parte)',url:'https://github.com/All-Hands-AI/OpenHands',basis:'leitura',
   what:'Agente que executa código e comandos, com isolamento opcional por Docker.',
   why:'O BBrainX não executa nada: serviço de memória com shell é risco sem contrapartida. O OpenHands pode consumir o contexto por MCP, como qualquer harness.',
   evidence:'Esta máquina não tem Docker; o diagnóstico informa isso em vez de tentar instalar.',
   change:'Nada no núcleo. Como cliente, já funciona pela configuração de MCP.'},
  {id:'x99',group:'out',name:'Dossiê X99 Power Code V4.0',kind:'documento de terceiros',license:'não se aplica (documento recebido)',url:'https://github.com/oalexandrebelo/BBrainX/blob/main/docs/FEASIBILITY.md',basis:'leitura',
   what:'Promete um ambiente pronto com doze ferramentas e arquivos de configuração «de produção».',
   why:'O script de instalação cria pastas e cinco arquivos, não instala nenhuma ferramenta e termina anunciando o ambiente pronto. Das 47 chaves de configuração conferidas, 20 não existem nos projetos citados.',
   evidence:'Script lido linha a linha. Chaves como laya.enableRouting, obsidian_sync e pixel-agents.layout não aparecem no código dos respectivos projetos.',
   change:'Nada. Serviu de lista do que conferir.'},
  {id:'x99-stack',group:'out',name:'Pilha do X99: Biome, MetaGPT, kbar…',kind:'e MagicUI, Pixel-Agents, public-apis',license:'variadas',url:'https://biomejs.dev/',basis:'leitura',
   what:'Formatador, arcabouço multiagente, paleta de comandos, componentes visuais, telemetria animada e uma lista de APIs.',
   why:'Nenhum resolve contexto, memória ou continuidade. São escolhas do projeto do usuário, não de um motor que serve qualquer projeto.',
   evidence:'Os números do dossiê («menos de 5 ms», «100 vezes») não têm fonte nos sites dos projetos, segundo a leitura.',
   change:'Emitir uma regra de editor ou uma skill com texto do próprio BBrainX é barato e pode entrar.'}
];
